/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.telasaida;

import dao.DaoSaida;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Saida;

/**
 *
 * @author emanu
 */
public class TelaConsultarSaida extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaConsultarSaida
     */
    public TelaConsultarSaida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSaida = new javax.swing.JTable();
        btnMostarTodos = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tabelaSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Lote", "Distribuidora", "Gerente", "Data de Saída"
            }
        ));
        jScrollPane1.setViewportView(tabelaSaida);
        if (tabelaSaida.getColumnModel().getColumnCount() > 0) {
            tabelaSaida.getColumnModel().getColumn(1).setResizable(false);
        }

        btnMostarTodos.setText("Mostrar Todos");
        btnMostarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostarTodos)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnMostarTodos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(!txtId.getText().trim().isEmpty()){
            int id = Integer.parseInt(txtId.getText());
            DefaultTableModel ts = (DefaultTableModel)tabelaSaida.getModel();
            ts.setNumRows(0);
            DaoSaida ds = new DaoSaida();
            Saida saida = new Saida();
            saida = ds.busca(id);
            System.out.println(saida.getLote().getId());
            if(saida == null){
                JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado!");
            }else{
                Object[] dados = {saida.getId(), saida.getLote().getId(), saida.getDistribuidora().getNome(), saida.getGerente().getNome(), saida.getDataDeSaida().toString()};
                ts.addRow(dados);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Digite um ID!");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarTodosActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tc = (DefaultTableModel)tabelaSaida.getModel();
        tc.setNumRows(0);
        DaoSaida ds = new DaoSaida();
        ArrayList<Saida> saida = new ArrayList<Saida>();
        saida = ds.mostraSaidas();
        if(saida.size() == 0){
            JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado!");
        }else{
            for(int i =0; i<saida.size(); i++) {
                Object[] dados = {saida.get(i).getId(), saida.get(i).getLote().getId(), saida.get(i).getDistribuidora().getNome(), saida.get(i).getGerente().getNome(), saida.get(i).getDataDeSaida().toString()};
                tc.addRow(dados);
            }
        }
    }//GEN-LAST:event_btnMostarTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaSaida;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
