/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.telasaida;

import dao.DaoDistribuidora;
import dao.DaoGerente;
import dao.DaoLote;
import dao.DaoSaida;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Distribuidora;
import model.Gerente;
import model.Lote;
import model.Saida;

/**
 *
 * @author emanu
 */
public class TelaAlterarSaida extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAlterarSaida
     */
    public TelaAlterarSaida() {
        initComponents();
        DaoGerente dg = new DaoGerente();
        ArrayList<Gerente> gerentes = new ArrayList<Gerente>();
        gerentes = dg.mostraTodos();
        cbGerente.removeAllItems();
        for(int i = 0; i< gerentes.size(); i++){
            cbGerente.addItem(gerentes.get(i).getNome());
        }
        
        DaoLote dl = new DaoLote();
        ArrayList<Lote> lotes = new ArrayList<Lote>();
        lotes = dl.mostraLotes();
        cbLote.removeAllItems();
        for(int i = 0; i< lotes.size(); i++){
            cbLote.addItem(""+lotes.get(i).getId());
        }
        
        DaoDistribuidora dd = new DaoDistribuidora();
        ArrayList<Distribuidora> distribuidoras = new ArrayList<Distribuidora>();
        distribuidoras = dd.mostraDistribuidora();
        cbDistribuidora.removeAllItems();
        for(int i = 0; i< distribuidoras.size(); i++){
            cbDistribuidora.addItem(distribuidoras.get(i).getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnMostarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSaida = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbLote = new javax.swing.JComboBox<>();
        cbGerente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbDistribuidora = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDataSaida = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnMostarTodos.setText("Mostrar Todos");
        btnMostarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostarTodosActionPerformed(evt);
            }
        });

        tabelaSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Lote", "Distribuidora", "Gerente", "Data de Saída"
            }
        ));
        tabelaSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSaidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSaida);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Lote(ID):");

        cbLote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbGerente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Gerente:");

        cbDistribuidora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Distribuidora:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data:");

        try {
            txtDataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbLote, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbDistribuidora, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5)
                                        .addGap(55, 55, 55)
                                        .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar)
                                .addGap(30, 30, 30)
                                .addComponent(btnMostarTodos)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnMostarTodos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbDistribuidora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(!txtId.getText().trim().isEmpty()){
            int id = Integer.parseInt(txtId.getText());
            DefaultTableModel ts = (DefaultTableModel)tabelaSaida.getModel();
            ts.setNumRows(0);
            DaoSaida ds = new DaoSaida();
            Saida saida = new Saida();
            saida = ds.busca(id);
            System.out.println(saida.getLote().getId());
            if(saida == null){
                JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado!");
            }else{
                Object[] dados = {saida.getId(), saida.getLote().getId(), saida.getDistribuidora().getNome(), saida.getGerente().getNome(), saida.getDataDeSaida().toString()};
                ts.addRow(dados);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Digite um ID!");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarTodosActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tc = (DefaultTableModel)tabelaSaida.getModel();
        tc.setNumRows(0);
        DaoSaida ds = new DaoSaida();
        ArrayList<Saida> saida = new ArrayList<Saida>();
        saida = ds.mostraSaidas();
        if(saida.size() == 0){
            JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado!");
        }else{
            for(int i =0; i<saida.size(); i++) {
                Object[] dados = {saida.get(i).getId(), saida.get(i).getLote().getId(), saida.get(i).getDistribuidora().getNome(), saida.get(i).getGerente().getNome(), saida.get(i).getDataDeSaida().toString()};
                tc.addRow(dados);
            }
        }
    }//GEN-LAST:event_btnMostarTodosActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String dataSaida = txtDataSaida.getText();
        
        DaoGerente dg = new DaoGerente();
        ArrayList<Gerente> gerente = dg.buscaNome(cbGerente.getSelectedItem().toString());
        
        DaoDistribuidora dd = new DaoDistribuidora();
        ArrayList<Distribuidora> distribuidora = dd.buscaNome(cbDistribuidora.getSelectedItem().toString());
       
        DaoLote dl = new DaoLote();
        Lote lote = dl.busca(Integer.parseInt(cbLote.getSelectedItem().toString()));
        lote.setDisponivel(false);
        dl.update(lote);
        if(!txtDataSaida.getText().trim().isEmpty()){
            DaoSaida ds = new DaoSaida();
            int row = tabelaSaida.getSelectedRow();
            Saida saida = ds.busca(Integer.parseInt(tabelaSaida.getValueAt(row, 0).toString()));
            saida.setDataDeSaida(dataSaida);
            saida.setDistribuidora(distribuidora.get(0));
            saida.setGerente(gerente.get(0));
            saida.setLote(lote);
            ds.update(saida);
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tabelaSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSaidaMouseClicked
        // TODO add your handling code here:
        int row = tabelaSaida.getSelectedRow();
        cbGerente.setSelectedItem(tabelaSaida.getValueAt(row, 3).toString());
        cbDistribuidora.setSelectedItem(tabelaSaida.getValueAt(row, 2).toString());
        cbLote.setSelectedItem(tabelaSaida.getValueAt(row, 1).toString());
        txtDataSaida.setText(tabelaSaida.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tabelaSaidaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostarTodos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbDistribuidora;
    private javax.swing.JComboBox<String> cbGerente;
    private javax.swing.JComboBox<String> cbLote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaSaida;
    private javax.swing.JFormattedTextField txtDataSaida;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
