/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.telaslote;

import dao.DaoFornecedora;
import dao.DaoGerente;
import dao.DaoLote;
import dao.DaoProduto;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Fornecedora;
import model.Gerente;
import model.Lote;
import model.Produto;

/**
 *
 * @author emanu
 */
public class TelaAlterarLote extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAlterarLote
     */
    public TelaAlterarLote() {
        initComponents();
        DaoGerente dg = new DaoGerente();
        ArrayList<Gerente> gerentes = new ArrayList<Gerente>();
        gerentes = dg.mostraTodos();
        cbGerente.removeAllItems();
        for(int i = 0; i< gerentes.size(); i++){
            cbGerente.addItem(gerentes.get(i).getNome());
        }
        
        DaoFornecedora df = new DaoFornecedora();
        ArrayList<Fornecedora> fornecedoras = new ArrayList<Fornecedora>();
        fornecedoras = df.mostraFornecedora();
        cbFornecedora.removeAllItems();
        for(int i = 0; i< fornecedoras.size(); i++){
            cbFornecedora.addItem(fornecedoras.get(i).getNome());
        }
        
        DaoProduto dp = new DaoProduto();
        ArrayList<Produto> produtos = new ArrayList<Produto>();
        produtos = dp.mostraTodos();
        cbProduto.removeAllItems();
        for(int i = 0; i< produtos.size(); i++){
            cbProduto.addItem(produtos.get(i).getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLote = new javax.swing.JTable();
        btnMostrarTodos = new javax.swing.JButton();
        txtValidade = new javax.swing.JFormattedTextField();
        txtDataDeEntrada = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQtdProduto = new javax.swing.JTextField();
        cbGerente = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbFornecedora = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tabelaLote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Gerente", "Fornecedora", "Produto", "Quantidade de Produto", "Validade", "Data de Entrada"
            }
        ));
        tabelaLote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLoteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLote);

        btnMostrarTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMostrarTodos.setText("Mostrar Todos");
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });

        try {
            txtValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataDeEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Quantidade: ");

        cbGerente.setSelectedItem(null
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Gerente:");

        cbFornecedora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Fornecedora");

        cbProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Produto");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Validade:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Data de Entrada");

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbFornecedora, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtQtdProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValidade)
                                    .addComponent(txtDataDeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnMostrarTodos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbFornecedora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDataDeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        if(!txtId.getText().trim().isEmpty()){

            int id = Integer.parseInt(txtId.getText());

            DefaultTableModel tl = (DefaultTableModel)tabelaLote.getModel();
            tl.setNumRows(0);
            DaoLote dl = new DaoLote();
            Lote lote = new Lote();
            lote = dl.busca(id);

            if(lote == null){
                JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado!");
            }else{
                Object[] dados = {lote.getId(), lote.getGerente().getNome(), lote.getFornecedora().getNome(), lote.getProduto().getNome(), lote.getQtdProduto(), lote.getValidade().toString(), lote.getDataDeEntrada().toString()};
                tl.addRow(dados);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Insira um ID!");
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tl = (DefaultTableModel)tabelaLote.getModel();
        tl.setNumRows(0);
        DaoLote dl = new DaoLote();
        ArrayList<Lote> lote = new ArrayList<Lote>();
        lote = dl.mostraLotes();
        if(lote.size() == 0){
            JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado!");
        }else{
            for(int i =0; i<lote.size(); i++) {
                Object[] dados = {lote.get(i).getId(), lote.get(i).getGerente().getNome(), lote.get(i).getFornecedora().getNome(), lote.get(i).getProduto().getNome(), lote.get(i).getQtdProduto(), lote.get(i).getValidade().toString(), lote.get(i).getDataDeEntrada().toString()};
                tl.addRow(dados);
            }
        }
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void tabelaLoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLoteMouseClicked
        // TODO add your handling code here:
        int row = tabelaLote.getSelectedRow();
        txtQtdProduto.setText(tabelaLote.getValueAt(row, 4).toString());
        cbGerente.setSelectedItem(tabelaLote.getValueAt(row, 1));
        cbFornecedora.setSelectedItem(tabelaLote.getValueAt(row, 2));
        cbProduto.setSelectedItem(tabelaLote.getValueAt(row, 3));
        txtValidade.setText(tabelaLote.getValueAt(row, 5).toString());
        txtDataDeEntrada.setText(tabelaLote.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tabelaLoteMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        DaoLote dl = new DaoLote();
        String gerente = cbGerente.getSelectedItem().toString();
        String fornecedora = cbFornecedora.getSelectedItem().toString();
        String produto = cbProduto.getSelectedItem().toString();
        int qtdProduto = Integer.parseInt(txtQtdProduto.getText());
        String validade = txtValidade.getText();
        String dataDeEntrada = txtDataDeEntrada.getText();
        
        Date dataValidade = null;
        Date dataEntrada = null;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            dataValidade = formato.parse(validade);
            dataEntrada = formato.parse(dataDeEntrada);
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastrarLote.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        long dt = ((dataValidade.getTime() - dataEntrada.getTime()) + 3600000 )/ 86400000L;

        
        if(dt>0 && !txtQtdProduto.getText().trim().isEmpty() && !txtValidade.getText().trim().isEmpty() && !txtDataDeEntrada.getText().trim().isEmpty()){
            int row = tabelaLote.getSelectedRow();
            Lote lote = null;
            lote = dl.busca(Integer.parseInt(tabelaLote.getValueAt(row, 0).toString()));
            lote.setDataDeEntrada(dataDeEntrada);
            lote.setValidade(validade);
            lote.setQtdProduto(qtdProduto);
                
            DaoGerente dc = new DaoGerente();
            ArrayList<Gerente> gerentes = dc.buscaNome(cbGerente.getSelectedItem().toString());

            DaoFornecedora df = new DaoFornecedora();
            ArrayList<Fornecedora> fornecedoras = df.buscaNome(cbFornecedora.getSelectedItem().toString());

            DaoProduto dp = new DaoProduto();
            ArrayList<Produto> produtos = dp.buscaNome(cbProduto.getSelectedItem().toString());
                
            lote.setFornecedora(fornecedoras.get(0));
            lote.setGerente(gerentes.get(0));
            System.out.println(lote.getGerente().getId());
            lote.setProduto(produtos.get(0));
                
            
            dl.update(lote);
        }
        else{
            JOptionPane.showMessageDialog(null, "Os campos devem estar preenchidos corretamente!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbFornecedora;
    private javax.swing.JComboBox cbGerente;
    private javax.swing.JComboBox cbProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLote;
    private javax.swing.JFormattedTextField txtDataDeEntrada;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtQtdProduto;
    private javax.swing.JFormattedTextField txtValidade;
    // End of variables declaration//GEN-END:variables
}
